name: Publish to GitHub NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./TestApp/TestApp.csproj

      - name: Build
        run: dotnet build ./TestApp/TestApp.csproj --configuration Release

      - name: Pack
        run: dotnet pack ./TestApp/TestApp.csproj --configuration Release --output ./nupkg

      - name: Add GitHub NuGet source
        run: dotnet nuget add source \
          --username $GITHUB_ACTOR \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Push to GitHub NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" \
          --source "github" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate
